//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitFirst.Landing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitFirst.Landing.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years’ Сlient engagement.
        /// </summary>
        public static string ABOUT_CLIENT_ENGAGEMENT {
            get {
                return ResourceManager.GetString("ABOUT_CLIENT_ENGAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string ABOUT_COUNTRIES {
            get {
                return ResourceManager.GetString("ABOUT_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your business digital transformation on the right foot..
        /// </summary>
        public static string ABOUT_MISSION {
            get {
                return ResourceManager.GetString("ABOUT_MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re on a mission to make it easy for anyone to start a business digital transformation. With our AI-powered business plan generator, you can get a comprehensive business plan in minutes and your digital solution free..
        /// </summary>
        public static string ABOUT_MISSION_DETAILS {
            get {
                return ResourceManager.GetString("ABOUT_MISSION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established in 2011, UnitFirst is a software development studio with a proud history of delivering high-quality solutions to clients across various industries. With 14 years of experience under our belt, we&apos;ve honed our skills in developing innovative, scalable, and reliable software products that meet the evolving needs of our clients..
        /// </summary>
        public static string ABOUT_ORGANIZATION_MAIN {
            get {
                return ResourceManager.GetString("ABOUT_ORGANIZATION_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction rate.
        /// </summary>
        public static string ABOUT_SATISFACTION_RATE {
            get {
                return ResourceManager.GetString("ABOUT_SATISFACTION_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior specialists.
        /// </summary>
        public static string ABOUT_SENIOR_SPECIALISTS {
            get {
                return ResourceManager.GetString("ABOUT_SENIOR_SPECIALISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful projects.
        /// </summary>
        public static string ABOUT_SUCCESSFUL_PROJECTS {
            get {
                return ResourceManager.GetString("ABOUT_SUCCESSFUL_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years on the market.
        /// </summary>
        public static string ABOUT_YEARS_ON_MARKET {
            get {
                return ResourceManager.GetString("ABOUT_YEARS_ON_MARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Projects.
        /// </summary>
        public static string CASES_ACCENT_WORD {
            get {
                return ResourceManager.GetString("CASES_ACCENT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Solutions for Healthcare.
        /// </summary>
        public static string CASES_AI_HEALTH {
            get {
                return ResourceManager.GetString("CASES_AI_HEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented AI chatbots and predictive analytics in healthcare systems to accelerate patient diagnosis, enhance treatment results, and streamline administration..
        /// </summary>
        public static string CASES_AI_HEALTH_DESC {
            get {
                return ResourceManager.GetString("CASES_AI_HEALTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/media-lab.svg.
        /// </summary>
        public static string CASES_AI_HEALTH_IMG {
            get {
                return ResourceManager.GetString("CASES_AI_HEALTH_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Solutions for Healthcare.
        /// </summary>
        public static string CASES_AI_HEALTH_URL {
            get {
                return ResourceManager.GetString("CASES_AI_HEALTH_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain Supply Chain Platform.
        /// </summary>
        public static string CASES_BLOCK_CHAIN {
            get {
                return ResourceManager.GetString("CASES_BLOCK_CHAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed a blockchain platform for supply chain management, offering end-to-end visibility, improved tracking, and better collaboration among all parties..
        /// </summary>
        public static string CASES_BLOCK_CHAIN_DESC {
            get {
                return ResourceManager.GetString("CASES_BLOCK_CHAIN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/marketing-lab.svg.
        /// </summary>
        public static string CASES_BLOCK_CHAIN_IMG {
            get {
                return ResourceManager.GetString("CASES_BLOCK_CHAIN_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain Supply Chain Platform.
        /// </summary>
        public static string CASES_BLOCK_CHAIN_URL {
            get {
                return ResourceManager.GetString("CASES_BLOCK_CHAIN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single glance tells the story..
        /// </summary>
        public static string CASES_DESC {
            get {
                return ResourceManager.GetString("CASES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string CASES_EDUCATION {
            get {
                return ResourceManager.GetString("CASES_EDUCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We enhance the educational journey with innovative EdTech solutions, from student portals to online course management, delivering intuitive and accessible e-learning platforms..
        /// </summary>
        public static string CASES_EDUCATION_DESC {
            get {
                return ResourceManager.GetString("CASES_EDUCATION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/education-lab.svg.
        /// </summary>
        public static string CASES_EDUCATION_IMG {
            get {
                return ResourceManager.GetString("CASES_EDUCATION_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string CASES_EDUCATION_URL {
            get {
                return ResourceManager.GetString("CASES_EDUCATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string CASES_ESTATE {
            get {
                return ResourceManager.GetString("CASES_ESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empower real estate operations with custom solutions for client management, deal tracking, and offer optimization, including property management, virtual tours, and live listings..
        /// </summary>
        public static string CASES_ESTATE_DESC {
            get {
                return ResourceManager.GetString("CASES_ESTATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/real-estate-lab.svg.
        /// </summary>
        public static string CASES_ESTATE_IMG {
            get {
                return ResourceManager.GetString("CASES_ESTATE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string CASES_ESTATE_URL {
            get {
                return ResourceManager.GetString("CASES_ESTATE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance and Accounting Automation.
        /// </summary>
        public static string CASES_FINANCES {
            get {
                return ResourceManager.GetString("CASES_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created an AI-powered automation platform for finance and accounting, reducing manual work, minimizing errors, and allowing staff to focus on higher-value activities..
        /// </summary>
        public static string CASES_FINANCES_DESC {
            get {
                return ResourceManager.GetString("CASES_FINANCES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/finances-lab.svg.
        /// </summary>
        public static string CASES_FINANCES_IMG {
            get {
                return ResourceManager.GetString("CASES_FINANCES_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance and Accounting Automation.
        /// </summary>
        public static string CASES_FINANCES_URL {
            get {
                return ResourceManager.GetString("CASES_FINANCES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string CASES_GET_DETAILS {
            get {
                return ResourceManager.GetString("CASES_GET_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Management for Small Business.
        /// </summary>
        public static string CASES_HR {
            get {
                return ResourceManager.GetString("CASES_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed a cloud HR management solution for small businesses, featuring customizable workflows, employee self-service, and compliance reporting to streamline HR tasks..
        /// </summary>
        public static string CASES_HR_DESC {
            get {
                return ResourceManager.GetString("CASES_HR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/marketing-lab.svg.
        /// </summary>
        public static string CASES_HR_IMG {
            get {
                return ResourceManager.GetString("CASES_HR_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Management for Small Business.
        /// </summary>
        public static string CASES_HR_URL {
            get {
                return ResourceManager.GetString("CASES_HR_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate E-Learning Platform.
        /// </summary>
        public static string CASES_LEARNING {
            get {
                return ResourceManager.GetString("CASES_LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built a scalable, cloud-based platform for corporate e-learning, enabling organizations to design and manage custom courses, monitor employee progress, and assess ROI..
        /// </summary>
        public static string CASES_LEARNING_DESC {
            get {
                return ResourceManager.GetString("CASES_LEARNING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/healthcare-lab.svg.
        /// </summary>
        public static string CASES_LEARNING_IMG {
            get {
                return ResourceManager.GetString("CASES_LEARNING_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate E-Learning Platform.
        /// </summary>
        public static string CASES_LEARNING_URL {
            get {
                return ResourceManager.GetString("CASES_LEARNING_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Analytics and Optimization.
        /// </summary>
        public static string CASES_MARKETING {
            get {
                return ResourceManager.GetString("CASES_MARKETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built a cloud platform for digital marketers, delivering real-time analytics, data visualization, and AI-driven optimization to maximize campaign ROI..
        /// </summary>
        public static string CASES_MARKETING_DESC {
            get {
                return ResourceManager.GetString("CASES_MARKETING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/marketing-lab.svg.
        /// </summary>
        public static string CASES_MARKETING_IMG {
            get {
                return ResourceManager.GetString("CASES_MARKETING_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Analytics and Optimization.
        /// </summary>
        public static string CASES_MARKETING_URL {
            get {
                return ResourceManager.GetString("CASES_MARKETING_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Predictive Maintenance.
        /// </summary>
        public static string CASES_PREDICTIVE {
            get {
                return ResourceManager.GetString("CASES_PREDICTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created an IoT-based predictive maintenance platform for industrial equipment, helping manufacturers detect issues early, schedule service, and reduce downtime..
        /// </summary>
        public static string CASES_PREDICTIVE_DESC {
            get {
                return ResourceManager.GetString("CASES_PREDICTIVE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/marketing-lab.svg.
        /// </summary>
        public static string CASES_PREDICTIVE_IMG {
            get {
                return ResourceManager.GetString("CASES_PREDICTIVE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Predictive Maintenance.
        /// </summary>
        public static string CASES_PREDICTIVE_URL {
            get {
                return ResourceManager.GetString("CASES_PREDICTIVE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Operations Optimization.
        /// </summary>
        public static string CASES_RETAIL {
            get {
                return ResourceManager.GetString("CASES_RETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed a mobile solution for retail operations, enabling staff to manage inventory, monitor sales, and optimize store performance in real time..
        /// </summary>
        public static string CASES_RETAIL_DESC {
            get {
                return ResourceManager.GetString("CASES_RETAIL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ecommerce-lab.svg.
        /// </summary>
        public static string CASES_RETAIL_IMG {
            get {
                return ResourceManager.GetString("CASES_RETAIL_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Operations Optimization.
        /// </summary>
        public static string CASES_RETAIL_URL {
            get {
                return ResourceManager.GetString("CASES_RETAIL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Cybersecurity for SMEs.
        /// </summary>
        public static string CASES_SME {
            get {
                return ResourceManager.GetString("CASES_SME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed a subscription-based, cloud cybersecurity platform for small and medium businesses, providing real-time threat detection, incident management, and compliance tools..
        /// </summary>
        public static string CASES_SME_DESC {
            get {
                return ResourceManager.GetString("CASES_SME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/logistics-lab.svg.
        /// </summary>
        public static string CASES_SME_IMG {
            get {
                return ResourceManager.GetString("CASES_SME_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Cybersecurity for SMEs.
        /// </summary>
        public static string CASES_SME_URL {
            get {
                return ResourceManager.GetString("CASES_SME_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher Ed Student Information System.
        /// </summary>
        public static string CASES_STUDENT {
            get {
                return ResourceManager.GetString("CASES_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented a comprehensive student information system for higher education, centralizing registration, course enrollment, and academic tracking..
        /// </summary>
        public static string CASES_STUDENT_DESC {
            get {
                return ResourceManager.GetString("CASES_STUDENT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/marketing-lab.svg.
        /// </summary>
        public static string CASES_STUDENT_IMG {
            get {
                return ResourceManager.GetString("CASES_STUDENT_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher Ed Student Information System.
        /// </summary>
        public static string CASES_STUDENT_URL {
            get {
                return ResourceManager.GetString("CASES_STUDENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully delivered solutions.
        /// </summary>
        public static string CASES_TITLE {
            get {
                return ResourceManager.GetString("CASES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penya Gofman, Head of SelfMade.
        /// </summary>
        public static string FEEDBACK_ITEM_0_AUTHOR {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_0_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our employees now benefit from low management fees, access to diverse investment options, as well as great perks to support their financial wellness. The plan transfer required a minimal time investment from our end, and the administration is simple!.
        /// </summary>
        public static string FEEDBACK_ITEM_0_DETAILS {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_0_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting UnitFirst for SelfMade, we were able to enhance our benefit program while saving on plan costs and management fees..
        /// </summary>
        public static string FEEDBACK_ITEM_0_MAIN {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_0_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosi Bosi, Head of SuperCompany.
        /// </summary>
        public static string FEEDBACK_ITEM_1_AUTHOR {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_1_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our employees now benefit from low management fees, access to diverse investment options, as well as great perks to support their financial wellness. The plan transfer required a minimal time investment from our end, and the administration is simple!.
        /// </summary>
        public static string FEEDBACK_ITEM_1_DETAILS {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_1_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting UnitFirst for SuperCompany, we were able to enhance our benefit program while saving on plan costs and management fees..
        /// </summary>
        public static string FEEDBACK_ITEM_1_MAIN {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_1_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tony Montana, Head of MontanaInc.
        /// </summary>
        public static string FEEDBACK_ITEM_2_AUTHOR {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_2_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our employees now benefit from low management fees, access to diverse investment options, as well as great perks to support their financial wellness. The plan transfer required a minimal time investment from our end, and the administration is simple!.
        /// </summary>
        public static string FEEDBACK_ITEM_2_DETAILS {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_2_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting UnitFirst for MontanaInc, we were able to enhance our benefit program while saving on plan costs and management fees..
        /// </summary>
        public static string FEEDBACK_ITEM_2_MAIN {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_2_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Yurik, Head of PokerGamer.
        /// </summary>
        public static string FEEDBACK_ITEM_3_AUTHOR {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_3_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our employees now benefit from low management fees, access to diverse investment options, as well as great perks to support their financial wellness. The plan transfer required a minimal time investment from our end, and the administration is simple!.
        /// </summary>
        public static string FEEDBACK_ITEM_3_DETAILS {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_3_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting UnitFirst for PokerGamer, we were able to enhance our benefit program while saving on plan costs and management fees..
        /// </summary>
        public static string FEEDBACK_ITEM_3_MAIN {
            get {
                return ResourceManager.GetString("FEEDBACK_ITEM_3_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York, NY 10311, US.
        /// </summary>
        public static string FOOTER_CONTACT_0 {
            get {
                return ResourceManager.GetString("FOOTER_CONTACT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@projectfabric.com.
        /// </summary>
        public static string FOOTER_CONTACT_1 {
            get {
                return ResourceManager.GetString("FOOTER_CONTACT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 01 234 567 88.
        /// </summary>
        public static string FOOTER_CONTACT_2 {
            get {
                return ResourceManager.GetString("FOOTER_CONTACT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 01 234 567 89.
        /// </summary>
        public static string FOOTER_CONTACT_3 {
            get {
                return ResourceManager.GetString("FOOTER_CONTACT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string FOOTER_CONTACTS {
            get {
                return ResourceManager.GetString("FOOTER_CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string FOOTER_DOCUMENT_0 {
            get {
                return ResourceManager.GetString("FOOTER_DOCUMENT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string FOOTER_DOCUMENT_1 {
            get {
                return ResourceManager.GetString("FOOTER_DOCUMENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string FOOTER_DOCUMENT_2 {
            get {
                return ResourceManager.GetString("FOOTER_DOCUMENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage cookies.
        /// </summary>
        public static string FOOTER_DOCUMENT_3 {
            get {
                return ResourceManager.GetString("FOOTER_DOCUMENT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string FOOTER_DOCUMENTS {
            get {
                return ResourceManager.GetString("FOOTER_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string FOOTER_LINK_0 {
            get {
                return ResourceManager.GetString("FOOTER_LINK_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FOOTER_LINK_1 {
            get {
                return ResourceManager.GetString("FOOTER_LINK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string FOOTER_LINK_2 {
            get {
                return ResourceManager.GetString("FOOTER_LINK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string FOOTER_LINK_3 {
            get {
                return ResourceManager.GetString("FOOTER_LINK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string FOOTER_LINKS {
            get {
                return ResourceManager.GetString("FOOTER_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string FOOTER_PRODUCTS {
            get {
                return ResourceManager.GetString("FOOTER_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business digital maintainer.
        /// </summary>
        public static string FOOTER_PRODUCTS_0 {
            get {
                return ResourceManager.GetString("FOOTER_PRODUCTS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market research.
        /// </summary>
        public static string FOOTER_PRODUCTS_1 {
            get {
                return ResourceManager.GetString("FOOTER_PRODUCTS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string FOOTER_PRODUCTS_2 {
            get {
                return ResourceManager.GetString("FOOTER_PRODUCTS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales and Marketing.
        /// </summary>
        public static string FOOTER_PRODUCTS_3 {
            get {
                return ResourceManager.GetString("FOOTER_PRODUCTS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved..
        /// </summary>
        public static string FOOTER_RIGHTS {
            get {
                return ResourceManager.GetString("FOOTER_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unitfirstgroup@gmail.com.
        /// </summary>
        public static string GET_IN_TOUCH_EMAIL {
            get {
                return ResourceManager.GetString("GET_IN_TOUCH_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love to hear from you! Send us a message with your idea using the contact details here and we&apos;ll generate solution for you soon as possible..
        /// </summary>
        public static string GET_IN_TOUCH_GREETING {
            get {
                return ResourceManager.GetString("GET_IN_TOUCH_GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch.
        /// </summary>
        public static string GET_IN_TOUCH_TITLE {
            get {
                return ResourceManager.GetString("GET_IN_TOUCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GET_STARTED {
            get {
                return ResourceManager.GetString("GET_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitFirst.
        /// </summary>
        public static string LABORATORIES_ACCENT_WORD {
            get {
                return ResourceManager.GetString("LABORATORIES_ACCENT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCommerce.
        /// </summary>
        public static string LABORATORIES_COMMERCE {
            get {
                return ResourceManager.GetString("LABORATORIES_COMMERCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We create web and mobile apps that strengthen customer relationships, offering a seamless shopping experience and round-the-clock availability..
        /// </summary>
        public static string LABORATORIES_COMMERCE_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_COMMERCE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ecommerce-lab.svg.
        /// </summary>
        public static string LABORATORIES_COMMERCE_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_COMMERCE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCommerce.
        /// </summary>
        public static string LABORATORIES_COMMERCE_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_COMMERCE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have developed deep expertise across many industries. Explore and find the most suitable lab for your needs..
        /// </summary>
        public static string LABORATORIES_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string LABORATORIES_EDUCATION {
            get {
                return ResourceManager.GetString("LABORATORIES_EDUCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We enhance education with custom EdTech solutions, from student portals to online course management, creating intuitive and accessible e-learning platforms..
        /// </summary>
        public static string LABORATORIES_EDUCATION_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_EDUCATION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/education-lab.svg.
        /// </summary>
        public static string LABORATORIES_EDUCATION_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_EDUCATION_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string LABORATORIES_EDUCATION_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_EDUCATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string LABORATORIES_ESTATE {
            get {
                return ResourceManager.GetString("LABORATORIES_ESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide solutions for customer management, deal tracking, and offer optimization, including property management, virtual tours, and real-time listings..
        /// </summary>
        public static string LABORATORIES_ESTATE_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_ESTATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/real-estate-lab.svg.
        /// </summary>
        public static string LABORATORIES_ESTATE_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_ESTATE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string LABORATORIES_ESTATE_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_ESTATE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string LABORATORIES_FINANCES {
            get {
                return ResourceManager.GetString("LABORATORIES_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We deliver wealth management, compliance, payment processing, insurance, budgeting, and planning tools—each built for security, scalability, and regulatory compliance..
        /// </summary>
        public static string LABORATORIES_FINANCES_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_FINANCES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/finances-lab.svg.
        /// </summary>
        public static string LABORATORIES_FINANCES_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_FINANCES_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string LABORATORIES_FINANCES_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_FINANCES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string LABORATORIES_GET_DETAILS {
            get {
                return ResourceManager.GetString("LABORATORIES_GET_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare.
        /// </summary>
        public static string LABORATORIES_HEALTHCARE {
            get {
                return ResourceManager.GetString("LABORATORIES_HEALTHCARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We develop patient management, medical platforms, IoT and AI-powered apps, analytics, and visualization tools. All solutions comply with HIPPA, GDPR, HITECH, FDA, and other standards..
        /// </summary>
        public static string LABORATORIES_HEALTHCARE_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_HEALTHCARE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/healthcare-lab.svg.
        /// </summary>
        public static string LABORATORIES_HEALTHCARE_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_HEALTHCARE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare.
        /// </summary>
        public static string LABORATORIES_HEALTHCARE_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_HEALTHCARE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        public static string LABORATORIES_LOGISTICS {
            get {
                return ResourceManager.GetString("LABORATORIES_LOGISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer real-time tracking, route optimization, inventory and fleet management, and process automation to keep your logistics operations running smoothly..
        /// </summary>
        public static string LABORATORIES_LOGISTICS_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_LOGISTICS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/logistics-lab.svg.
        /// </summary>
        public static string LABORATORIES_LOGISTICS_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_LOGISTICS_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        public static string LABORATORIES_LOGISTICS_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_LOGISTICS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string LABORATORIES_MARKETING {
            get {
                return ResourceManager.GetString("LABORATORIES_MARKETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We develop marketing automation tools to optimize strategies, gather insights, and help you achieve ambitious goals with your clients..
        /// </summary>
        public static string LABORATORIES_MARKETING_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_MARKETING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/marketing-lab.svg.
        /// </summary>
        public static string LABORATORIES_MARKETING_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_MARKETING_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string LABORATORIES_MARKETING_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_MARKETING_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media &amp; Entertainment.
        /// </summary>
        public static string LABORATORIES_MEDIA {
            get {
                return ResourceManager.GetString("LABORATORIES_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We build streaming platforms, recommendation engines, social media tools, event systems, and more—ensuring personalized experiences and high availability even during peak times..
        /// </summary>
        public static string LABORATORIES_MEDIA_DESC {
            get {
                return ResourceManager.GetString("LABORATORIES_MEDIA_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/media-lab.svg.
        /// </summary>
        public static string LABORATORIES_MEDIA_IMG {
            get {
                return ResourceManager.GetString("LABORATORIES_MEDIA_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media &amp; Entertainment.
        /// </summary>
        public static string LABORATORIES_MEDIA_URL {
            get {
                return ResourceManager.GetString("LABORATORIES_MEDIA_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a digital lab tailored to your needs....
        /// </summary>
        public static string LABORATORIES_SEARCH {
            get {
                return ResourceManager.GetString("LABORATORIES_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lab.
        /// </summary>
        public static string LABORATORIES_TITLE {
            get {
                return ResourceManager.GetString("LABORATORIES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string NAV_ABOUT {
            get {
                return ResourceManager.GetString("NAV_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string NAV_BLOG {
            get {
                return ResourceManager.GetString("NAV_BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string NAV_CASES {
            get {
                return ResourceManager.GetString("NAV_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string NAV_CONTACTS {
            get {
                return ResourceManager.GetString("NAV_CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratories.
        /// </summary>
        public static string NAV_LABORATORIES {
            get {
                return ResourceManager.GetString("NAV_LABORATORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string NAV_SERVICES {
            get {
                return ResourceManager.GetString("NAV_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string NEWSLETTER {
            get {
                return ResourceManager.GetString("NEWSLETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to stay in the loop with the latest features and updates!.
        /// </summary>
        public static string NEWSLETTER_DESC {
            get {
                return ResourceManager.GetString("NEWSLETTER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string NEWSLETTER_SUBSCRIBE {
            get {
                return ResourceManager.GetString("NEWSLETTER_SUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitFirst.
        /// </summary>
        public static string ORGANIZATION {
            get {
                return ResourceManager.GetString("ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality and care for our customers. Create a business plan and implementation with full coverage of quality and metrics..
        /// </summary>
        public static string ORGANIZATION_MANIFEST {
            get {
                return ResourceManager.GetString("ORGANIZATION_MANIFEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitFirst.
        /// </summary>
        public static string SERVICES_ACCENT_WORD {
            get {
                return ResourceManager.GetString("SERVICES_ACCENT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI solutions.
        /// </summary>
        public static string SERVICES_AI {
            get {
                return ResourceManager.GetString("SERVICES_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our AI services cover everything from predictive analytics to healthcare diagnostics. We specialize in custom AI models, machine learning, NLP, computer vision, and predictive maintenance tools..
        /// </summary>
        public static string SERVICES_AI_DESC {
            get {
                return ResourceManager.GetString("SERVICES_AI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ai-development.svg.
        /// </summary>
        public static string SERVICES_AI_IMG {
            get {
                return ResourceManager.GetString("SERVICES_AI_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI solutions.
        /// </summary>
        public static string SERVICES_AI_URL {
            get {
                return ResourceManager.GetString("SERVICES_AI_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a free consultation.
        /// </summary>
        public static string SERVICES_BOOK_CONSULTATION {
            get {
                return ResourceManager.GetString("SERVICES_BOOK_CONSULTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.
        /// </summary>
        public static string SERVICES_CAT_ACCENT_WORD {
            get {
                return ResourceManager.GetString("SERVICES_CAT_ACCENT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over the years, we’ve gained deep expertise in a variety of specialized services..
        /// </summary>
        public static string SERVICES_CAT_DESC {
            get {
                return ResourceManager.GetString("SERVICES_CAT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our service categories.
        /// </summary>
        public static string SERVICES_CAT_TITLE {
            get {
                return ResourceManager.GetString("SERVICES_CAT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored software solutions.
        /// </summary>
        public static string SERVICES_CUSTOM_DEVELOPMENT {
            get {
                return ResourceManager.GetString("SERVICES_CUSTOM_DEVELOPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We create custom solutions designed for your unique business needs. Our full-cycle development adapts to your budget, timeline, technology stack, and advanced requirements..
        /// </summary>
        public static string SERVICES_CUSTOM_DEVELOPMENT_DESC {
            get {
                return ResourceManager.GetString("SERVICES_CUSTOM_DEVELOPMENT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/custom-development.svg.
        /// </summary>
        public static string SERVICES_CUSTOM_DEVELOPMENT_IMG {
            get {
                return ResourceManager.GetString("SERVICES_CUSTOM_DEVELOPMENT_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored software solutions.
        /// </summary>
        public static string SERVICES_CUSTOM_DEVELOPMENT_URL {
            get {
                return ResourceManager.GetString("SERVICES_CUSTOM_DEVELOPMENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At UnitFirst, we deliver comprehensive software development, industry expertise, advisory services, and system maintenance—including legacy systems. Our engineering services support both outsourcing and team extension models..
        /// </summary>
        public static string SERVICES_DESC {
            get {
                return ResourceManager.GetString("SERVICES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string SERVICES_GET_IN_TOUCH {
            get {
                return ResourceManager.GetString("SERVICES_GET_IN_TOUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatGPT integration.
        /// </summary>
        public static string SERVICES_GPT {
            get {
                return ResourceManager.GetString("SERVICES_GPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate ChatGPT for 24/7 support, efficient customer service, and actionable insights. We offer consulting, customization, and seamless integration for web and mobile apps to boost engagement and retention..
        /// </summary>
        public static string SERVICES_GPT_DESC {
            get {
                return ResourceManager.GetString("SERVICES_GPT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/gpt-development.svg.
        /// </summary>
        public static string SERVICES_GPT_IMG {
            get {
                return ResourceManager.GetString("SERVICES_GPT_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatGPT integration.
        /// </summary>
        public static string SERVICES_GPT_URL {
            get {
                return ResourceManager.GetString("SERVICES_GPT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT solutions.
        /// </summary>
        public static string SERVICES_IOT {
            get {
                return ResourceManager.GetString("SERVICES_IOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We build IoT systems of any size, from small device fleets to large-scale deployments. Our expertise covers consulting, ROI analysis, opportunity identification, dashboard visualization, device management, security, and network optimization, backed by over a decade of successful projects..
        /// </summary>
        public static string SERVICES_IOT_DESC {
            get {
                return ResourceManager.GetString("SERVICES_IOT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/iot-platform.svg.
        /// </summary>
        public static string SERVICES_IOT_IMG {
            get {
                return ResourceManager.GetString("SERVICES_IOT_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT solutions.
        /// </summary>
        public static string SERVICES_IOT_URL {
            get {
                return ResourceManager.GetString("SERVICES_IOT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile app development.
        /// </summary>
        public static string SERVICES_MOBILE {
            get {
                return ResourceManager.GetString("SERVICES_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our skilled team crafts outstanding iOS, Android, and cross-platform apps with intuitive interfaces and engaging user experiences, helping your business grow by delighting users..
        /// </summary>
        public static string SERVICES_MOBILE_DESC {
            get {
                return ResourceManager.GetString("SERVICES_MOBILE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/mobile-development.svg.
        /// </summary>
        public static string SERVICES_MOBILE_IMG {
            get {
                return ResourceManager.GetString("SERVICES_MOBILE_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile app development.
        /// </summary>
        public static string SERVICES_MOBILE_URL {
            get {
                return ResourceManager.GetString("SERVICES_MOBILE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        public static string SERVICES_TITLE {
            get {
                return ResourceManager.GetString("SERVICES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application development.
        /// </summary>
        public static string SERVICES_WEB {
            get {
                return ResourceManager.GetString("SERVICES_WEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We deliver scalable, secure, and high-performance web apps. Each project is approached individually to ensure it meets user needs, drives growth, and remains competitive..
        /// </summary>
        public static string SERVICES_WEB_DESC {
            get {
                return ResourceManager.GetString("SERVICES_WEB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/web-development.svg.
        /// </summary>
        public static string SERVICES_WEB_IMG {
            get {
                return ResourceManager.GetString("SERVICES_WEB_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application development.
        /// </summary>
        public static string SERVICES_WEB_URL {
            get {
                return ResourceManager.GetString("SERVICES_WEB_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get connected with us on social networks:.
        /// </summary>
        public static string SOCIAL_NETWORKS_DESC {
            get {
                return ResourceManager.GetString("SOCIAL_NETWORKS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string TAG_BUSINESS {
            get {
                return ResourceManager.GetString("TAG_BUSINESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string TAG_EDUCATION {
            get {
                return ResourceManager.GetString("TAG_EDUCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare.
        /// </summary>
        public static string TAG_HEALTHCARE {
            get {
                return ResourceManager.GetString("TAG_HEALTHCARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string TAG_MEDIA {
            get {
                return ResourceManager.GetString("TAG_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string TAG_TRANSPORT {
            get {
                return ResourceManager.GetString("TAG_TRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitFirst is a leading IT company providing innovative solutions for businesses and individuals..
        /// </summary>
        public static string THESIS_0 {
            get {
                return ResourceManager.GetString("THESIS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string THESIS_0_ACTION {
            get {
                return ResourceManager.GetString("THESIS_0_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team of experienced professionals with a passion for technology and innovation. We are committed to delivering high-quality solutions that meet our clients&apos; needs and exceed their expectations..
        /// </summary>
        public static string THESIS_0_DESC {
            get {
                return ResourceManager.GetString("THESIS_0_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string THESIS_1 {
            get {
                return ResourceManager.GetString("THESIS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get More Info.
        /// </summary>
        public static string THESIS_1_ACTION {
            get {
                return ResourceManager.GetString("THESIS_1_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer a range of services including software development, IT consulting, cybersecurity, and more..
        /// </summary>
        public static string THESIS_1_DESC {
            get {
                return ResourceManager.GetString("THESIS_1_DESC", resourceCulture);
            }
        }
    }
}
