name: Build & Test 🧪

on:
  push:
    branches:
      - development

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 📂
        run: dotnet restore ./src/ProjectFabric.IdentityServer/ProjectFabric.IdentityServer.csproj

      - name: Build 🧱
        run: dotnet build ./src/ProjectFabric.IdentityServer/ProjectFabric.IdentityServer.csproj --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test ./src/ProjectFabric.IdentityServer/ProjectFabric.IdentityServer.csproj --configuration Release --no-build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/ProjectFabric.IdentityServer
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/projectfabric:identity-server-dev-latest